spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/new_store_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret-key: b5439e7f5737d4751d3e65d05e70e2277b64b5549615e559214b3051431ecb91020694f34622c5bc2b58eacd86bcc95efca33c365cae5564a892c92b11661550
  expiration: 24h

cloudinary:
  cloud_name: "dwzjwh6tb"
  api_key: "429168221755551"
  api_secret: "zRvcEGNZ5ZgnEFDf05_7DL4pcSo"
